// src/components/product/RichTextEditor.tsx
import React, { useEffect, useState } from "react";
import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  Bold,
  Italic,
  Link,
  List,
  ListOrdered,
  Redo2,
  Strikethrough,
  Underline,
  Undo2,
} from "../common/octicons-compat";

export const RichTextEditor: React.FC<{
  editor: React.RefObject<HTMLDivElement | null>;
  value?: string;
  htmlValue?: string;
  onInput: (text: string, html: string) => void;
  onBlur?: () => void;
  placeholder?: string;
}> = ({ editor, value = "", htmlValue = "", onInput, onBlur, placeholder = "请输入内容，支持文字排版、列表和链接..." }) => {
  const [linkUrl, setLinkUrl] = useState("");

  useEffect(() => {
    if (!editor.current) return;
    const next = htmlValue || value;
    if (next && editor.current.innerHTML !== next && document.activeElement !== editor.current) {
      editor.current.innerHTML = htmlValue || value.replace(/\n/g, "<br>");
    }
  }, [editor, htmlValue, value]);

  const emitInput = () => onInput(editor.current?.innerText || "", editor.current?.innerHTML || "");
  const command = (name: string, commandValue?: string) => {
    editor.current?.focus();
    document.execCommand(name, false, commandValue);
    emitInput();
  };
  const buttons: Array<{ label: string; icon: React.ReactNode; command: string; value?: string }> = [
    { label: "撤销", icon: <Undo2 className="h-4 w-4" />, command: "undo" },
    { label: "重做", icon: <Redo2 className="h-4 w-4" />, command: "redo" },
    { label: "粗体", icon: <Bold className="h-4 w-4" />, command: "bold" },
    { label: "斜体", icon: <Italic className="h-4 w-4" />, command: "italic" },
    { label: "下划线", icon: <Underline className="h-4 w-4" />, command: "underline" },
    { label: "删除线", icon: <Strikethrough className="h-4 w-4" />, command: "strikeThrough" },
    { label: "项目符号", icon: <List className="h-4 w-4" />, command: "insertUnorderedList" },
    { label: "编号列表", icon: <ListOrdered className="h-4 w-4" />, command: "insertOrderedList" },
    { label: "左对齐", icon: <AlignLeft className="h-4 w-4" />, command: "justifyLeft" },
    { label: "居中", icon: <AlignCenter className="h-4 w-4" />, command: "justifyCenter" },
    { label: "右对齐", icon: <AlignRight className="h-4 w-4" />, command: "justifyRight" },
  ];
  const handlePaste = (event: React.ClipboardEvent<HTMLDivElement>) => {
    const item = Array.from(event.clipboardData.items as DataTransferItem[]).find((entry) => entry.type.startsWith("image/"));
    if (!item) return;
    event.preventDefault();
    const file = item.getAsFile();
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => command("insertImage", String(reader.result));
    reader.readAsDataURL(file);
  };

  return (
    <div className="overflow-hidden rounded-lg border border-[var(--border-main)] bg-[var(--bg-card)] focus-within:border-[var(--primary)] focus-within:ring-2 focus-within:ring-[var(--primary)]/20">
      <div className="flex flex-wrap items-center gap-1 border-b border-[var(--border-main)] px-2 py-1">
        {buttons.map((item) => <button key={item.label} type="button" title={item.label} aria-label={item.label} onMouseDown={(event) => event.preventDefault()} onClick={() => command(item.command, item.value)} className="inline-flex h-8 w-8 items-center justify-center rounded text-[var(--text-muted)] hover:bg-[var(--bg-surface-soft)] hover:text-[var(--text-primary)]">{item.icon}</button>)}
        <div className="ml-1 flex items-center rounded border border-[var(--border-main)]">
          <Link className="ml-2 h-3.5 w-3.5 text-[var(--text-muted)]" />
          <input aria-label="链接地址" value={linkUrl} onChange={(event) => setLinkUrl(event.target.value)} placeholder="https://" className="h-7 w-28 bg-transparent px-2 text-xs text-[var(--text-primary)] outline-none" />
          <button type="button" disabled={!linkUrl.trim()} onMouseDown={(event) => event.preventDefault()} onClick={() => { command("createLink", linkUrl.trim()); setLinkUrl(""); }} className="h-7 border-l border-[var(--border-main)] px-2 text-xs text-[var(--active-text)] disabled:opacity-40">插入</button>
        </div>
      </div>
      <div ref={editor} contentEditable role="textbox" aria-multiline="true" suppressContentEditableWarning onPaste={handlePaste} onInput={emitInput} onBlur={onBlur} className="min-h-80 p-4 text-sm leading-6 text-[var(--text-primary)] outline-none empty:before:pointer-events-none empty:before:text-[var(--text-muted)] empty:before:content-[attr(data-placeholder)]" data-placeholder={placeholder} />
    </div>
  );
};

// frontend/src/components/product/RichTextEditor.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';
import {
  Undo2,
  Redo2,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  List,
  ListOrdered,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Link as LinkIcon
} from 'lucide-vue-next';

interface Props {
  modelValue?: string;
  htmlValue?: string;
  placeholder?: string;
}

interface Emits {
  (e: 'update:modelValue', text: string): void;
  (e: 'update:htmlValue', html: string): void;
  (e: 'blur'): void;
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '',
  htmlValue: '',
  placeholder: '请输入内容，支持文字排版、列表和链接...'
});

const emit = defineEmits<Emits>();

const editor = ref<HTMLDivElement | null>(null);
const linkUrl = ref('');

// 初始化内容
onMounted(() => {
  if (editor.value && (props.htmlValue || props.modelValue)) {
    editor.value.innerHTML = props.htmlValue || props.modelValue.replace(/\n/g, '<br>');
  }
});

// 监听外部变化
watch([() => props.htmlValue, () => props.modelValue], () => {
  if (!editor.value) return;
  const next = props.htmlValue || props.modelValue;
  if (next && editor.value.innerHTML !== next && document.activeElement !== editor.value) {
    editor.value.innerHTML = props.htmlValue || props.modelValue.replace(/\n/g, '<br>');
  }
});

// 发射变更
function emitInput() {
  if (!editor.value) return;
  const text = editor.value.innerText || '';
  const html = editor.value.innerHTML || '';
  emit('update:modelValue', text);
  emit('update:htmlValue', html);
}

// 执行命令
function command(name: string, value?: string) {
  editor.value?.focus();
  document.execCommand(name, false, value);
  emitInput();
}

// 工具栏按钮配置
const buttons = [
  { label: '撤销', icon: Undo2, command: 'undo' },
  { label: '重做', icon: Redo2, command: 'redo' },
  { label: '粗体', icon: Bold, command: 'bold' },
  { label: '斜体', icon: Italic, command: 'italic' },
  { label: '下划线', icon: Underline, command: 'underline' },
  { label: '删除线', icon: Strikethrough, command: 'strikeThrough' },
  { label: '项目符号', icon: List, command: 'insertUnorderedList' },
  { label: '编号列表', icon: ListOrdered, command: 'insertOrderedList' },
  { label: '左对齐', icon: AlignLeft, command: 'justifyLeft' },
  { label: '居中', icon: AlignCenter, command: 'justifyCenter' },
  { label: '右对齐', icon: AlignRight, command: 'justifyRight' }
];

// 插入链接
function insertLink() {
  if (!linkUrl.value.trim()) return;
  command('createLink', linkUrl.value.trim());
  linkUrl.value = '';
}

// 处理粘贴图片
function handlePaste(event: ClipboardEvent) {
  const items = Array.from(event.clipboardData?.items || []);
  const imageItem = items.find(item => item.type.startsWith('image/'));
  
  if (!imageItem) return;
  
  event.preventDefault();
  const file = imageItem.getAsFile();
  if (!file) return;
  
  const reader = new FileReader();
  reader.onload = () => {
    command('insertImage', String(reader.result));
  };
  reader.readAsDataURL(file);
}
</script>

<template>
  <div class="rich-text-editor">
    <div class="toolbar">
      <button
        v-for="btn in buttons"
        :key="btn.label"
        type="button"
        :title="btn.label"
        :aria-label="btn.label"
        class="toolbar-btn"
        @mousedown.prevent
        @click="command(btn.command)"
      >
        <component :is="btn.icon" :size="16" />
      </button>
      
      <div class="link-input-group">
        <LinkIcon :size="14" class="link-icon" />
        <input
          v-model="linkUrl"
          type="text"
          placeholder="https://"
          aria-label="链接地址"
          class="link-input"
        />
        <button
          type="button"
          class="link-insert-btn"
          :disabled="!linkUrl.trim()"
          @mousedown.prevent
          @click="insertLink"
        >
          插入
        </button>
      </div>
    </div>
    
    <div
      ref="editor"
      contenteditable="true"
      role="textbox"
      aria-multiline="true"
      class="editor-content"
      :data-placeholder="placeholder"
      @input="emitInput"
      @blur="emit('blur')"
      @paste="handlePaste"
    />
  </div>
</template>

<style scoped>
.rich-text-editor {
  overflow: hidden;
  border-radius: 8px;
  border: 1px solid var(--border-main);
  background: var(--bg-card);
}

.rich-text-editor:focus-within {
  border-color: var(--primary);
  box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.2);
}

.toolbar {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 4px;
  padding: 4px 8px;
  border-bottom: 1px solid var(--border-main);
}

.toolbar-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border: none;
  border-radius: 4px;
  background: transparent;
  color: var(--text-muted);
  cursor: pointer;
  transition: all 0.15s;
}

.toolbar-btn:hover {
  background: var(--bg-surface-soft);
  color: var(--text-primary);
}

.link-input-group {
  display: flex;
  align-items: center;
  margin-left: 4px;
  border: 1px solid var(--border-main);
  border-radius: 4px;
  overflow: hidden;
}

.link-icon {
  margin-left: 8px;
  color: var(--text-muted);
}

.link-input {
  width: 112px;
  height: 28px;
  padding: 0 8px;
  border: none;
  background: transparent;
  color: var(--text-primary);
  font-size: 12px;
  outline: none;
}

.link-insert-btn {
  height: 28px;
  padding: 0 8px;
  border: none;
  border-left: 1px solid var(--border-main);
  background: transparent;
  color: var(--active-text);
  font-size: 12px;
  cursor: pointer;
  transition: opacity 0.15s;
}

.link-insert-btn:disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.editor-content {
  min-height: 320px;
  padding: 16px;
  color: var(--text-primary);
  font-size: 14px;
  line-height: 1.6;
  outline: none;
}

.editor-content:empty::before {
  content: attr(data-placeholder);
  color: var(--text-muted);
  pointer-events: none;
}
</style>
